[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dvc_dat"
dependencies = [
    "pandas",
    "pydantic>=2.10.6",
    "pyyaml",
]
requires-python = ">= 3.8"
keywords = ["dvc"]
readme = "README.md"
dynamic = ["version"]

[project.scripts]
dat = "dvc_dat.__main__:main"

[tool.setuptools]
packages = ["dvc_dat"]

[tool.setuptools.dynamic]
version = {attr = "dvc_dat.__init__.__version__"}

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "nbconvert>=7.16.6",
    "pytest>=8.3.5",
    "xlsxwriter>=3.2.9",
]
